apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  # type: NodePort
  ports:
    - protocol: "TCP"
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper