apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: broker
spec:
  selector:
    matchLabels:
      app: broker
  replicas: 1
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:6.0.0
        env:
        - name: KAFKA_BROKER_ID
          value: '1'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper:2181'
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: '1'
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: '0'        
        - name: KAFKA_JMX_PORT
          value: '9101'
        - name: KAFKA_JMX_HOSTNAME
          value: localhost              
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 400Mi
        ports:
        - containerPort: 9092
        - containerPort: 9101
        - containerPort: 29092

---
