apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
spec:
  # type: NodePort
  ports:
    - name: "port1"
      protocol: "TCP"
      port: 9092
      targetPort: 9092
    - name: "port2"
      protocol: "TCP"
      port: 9101
      targetPort: 9101
    - name: "port3"
      protocol: "TCP"
      port: 29092
      targetPort: 29092
  selector:
    app: broker