##
## You provide this
##
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: main
spec:
  selector:
    matchLabels:
      app: main
  replicas: 1
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: madhuaithal/main_service
        # imagePullPolicy: Never
        env:
          - name: ES_HOST
            value: "elasticsearch"  
          - name: KAFKA_HOST
            value: ""
        # resources:
        #   requests:
        #     cpu: 200m
        #     memory: 800Mi
        ports:
        - containerPort: 5000
---
